name: Unit tests

on:
  push:
    branches:
      - master
  pull_request: { }
  workflow_dispatch: { }

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run docker
        uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: belbix/subgraph:matchstick
          options: -it --rm --mount type=bind,source={{ github.workspace }},target=/matchstick
