name: Unit tests

on:
  push:
    branches:
      - master
  pull_request: { }
  workflow_dispatch: { }

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: codegen
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
        env:
          NODE_OPTIONS: --max_old_space_size=4096
